# render.yaml
services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: |
      # Install CMake
      apt-get update
      apt-get install -y cmake

      # Install the dlib wheel first
      pip install ./package/dlib_binary-19.24.1-cp310-cp310-manylinux1_x86_64.whl

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    plan: free